#######################################################
############## RC PRIMAL CORE PROPERTIES ##############
#######################################################


liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml
  enabled: true
  drop-first: false

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:rcpc_database;USER=rcpc_user;PASSWORD=rcpc_pwd;DB_CLOSE_DELAY=-1;
    username: rcpc_user
    password: rcpc_pwd
    hikari:
      maximumPoolSize: 5
      minimumIdle: 3
